"""Initial migration

Revision ID: 5fa6a94dad12
Revises: d888566891bc
Create Date: 2024-08-18 19:09:36.013389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fa6a94dad12'
down_revision = 'd888566891bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_application')
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.alter_column('resume',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('cover_letter',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('posted_date', sa.DateTime(), nullable=False))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_column('company')
        batch_op.drop_column('date_posted')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_posted', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('company', sa.VARCHAR(length=120), nullable=False))
        batch_op.alter_column('location',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('posted_date')
        batch_op.drop_column('company_name')

    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.alter_column('cover_letter',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('resume',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    op.create_table('job_application',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('resume', sa.VARCHAR(length=120), nullable=False),
    sa.Column('cover_letter', sa.VARCHAR(length=120), nullable=True),
    sa.Column('applied_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
